import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "../components/header";
import Overview from "../components/overview";
import Events from "../components/events";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>DUTCH0x - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <Header />
        <div className="flex gap-6 p-6 bg-[#F5F5F5]">
          <Events />
          <Overview />
        </div>
      </main>
    </>
  );
}
